/**
 * A curated list of Google Material Symbols names.
 */
export const materialIcons = [
    // General
    { cat: 'general', name: 'home' }, { cat: 'general', name: 'search' }, { cat: 'general', name: 'settings' },
    { cat: 'general', name: 'done' }, { cat: 'general', name: 'close' }, { cat: 'general', name: 'menu' },
    { cat: 'general', name: 'add' }, { cat: 'general', name: 'remove' }, { cat: 'general', name: 'star' },
    { cat: 'general', name: 'favorite' }, { cat: 'general', name: 'more_vert' }, { cat: 'general', name: 'more_horiz' },
    { cat: 'general', name: 'arrow_back' }, { cat: 'general', name: 'arrow_forward' }, { cat: 'general', name: 'arrow_upward' },
    { cat: 'general', name: 'arrow_downward' }, { cat: 'general', name: 'check_circle' }, { cat: 'general', name: 'cancel' },
    { cat: 'general', name: 'info' }, { cat: 'general', name: 'help' }, { cat: 'general', name: 'warning' },
    { cat: 'general', name: 'error' }, { cat: 'general', name: 'account_circle' }, { cat: 'general', name: 'person' },
    { cat: 'general', name: 'group' }, { cat: 'general', name: 'public' }, { cat: 'general', name: 'language' },
    { cat: 'general', name: 'schedule' }, { cat: 'general', name: 'event' }, { cat: 'general', name: 'verified' },
    { cat: 'general', name: 'thumb_up' }, { cat: 'general', name: 'thumb_down' }, { cat: 'general', name: 'explore' },
    { cat: 'general', name: 'lock' }, { cat: 'general', name: 'fingerprint' }, { cat: 'general', name: 'bookmark' },
    { cat: 'general', name: 'build' }, { cat: 'general', name: 'emoji_events' },
    { cat: 'general', name: 'hub' }, { cat: 'general', name: 'api' },
    { cat: 'general', name: 'category' }, { cat: 'general', name: 'dashboard' }, { cat: 'general', name: 'grid_view' },
    { cat: 'general', name: 'view_list' }, { cat: 'general', name: 'view_module' }, { cat: 'general', name: 'view_quilt' },
    { cat: 'general', name: 'filter_list' }, { cat: 'general', name: 'sort' }, { cat: 'general', name: 'tune' },
    { cat: 'general', name: 'download' }, { cat: 'general', name: 'upload' }, { cat: 'general', name: 'print' },
    { cat: 'general', name: 'refresh' }, { cat: 'general', name: 'sync' }, { cat: 'general', name: 'open_in_new' },
    { cat: 'general', name: 'share' }, { cat: 'general', name: 'content_copy' }, { cat: 'general', name: 'undo' },
    { cat: 'general', name: 'redo' }, { cat: 'general', name: 'zoom_in' }, { cat: 'general', name: 'zoom_out' },
    { cat: 'general', name: 'lock_open' }, { cat: 'general', name: 'shield' }, { cat: 'general', name: 'verified_user' },
    { cat: 'general', name: 'privacy_tip' }, { cat: 'general', name: 'visibility' }, { cat: 'general', name: 'visibility_off' },
    { cat: 'general', name: 'block' }, { cat: 'general', name: 'admin_panel_settings' }, { cat: 'general', name: 'policy' },
    { cat: 'general', name: 'report' }, { cat: 'general', name: 'dangerous' }, { cat: 'general', name: 'encrypted' },
    { cat: 'general', name: 'vpn_key' }, { cat: 'general', name: 'gpp_good' }, { cat: 'general', name: 'notifications' },
    { cat: 'general', name: 'label' }, { cat: 'general', name: 'push_pin' }, { cat: 'general', name: 'interests' },
    { cat: 'general', name: 'auto_awesome' }, { cat: 'general', name: 'grade' }, { cat: 'general', name: 'new_releases' },

    // Files & Folders
    { cat: 'files', name: 'folder' }, { cat: 'files', name: 'folder_open' }, { cat: 'files', name: 'create_new_folder' },
    { cat: 'files', name: 'description' }, { cat: 'files', name: 'article' }, { cat: 'files', name: 'insert_drive_file' },
    { cat: 'files', name: 'note' }, { cat: 'files', name: 'save' }, { cat: 'files', name: 'cloud' },
    { cat: 'files', name: 'cloud_upload' }, { cat: 'files', name: 'cloud_download' }, { cat: 'files', name: 'cloud_done' },
    { cat: 'files', name: 'inventory_2' }, { cat: 'files', name: 'note_add' }, { cat: 'files', name: 'draft' },
    { cat: 'files', name: 'folder_copy' }, { cat: 'files', name: 'attachment' }, { cat: 'files', name: 'snippet_folder' },
    { cat: 'files', name: 'folder_zip' }, { cat: 'files', name: 'topic' }, { cat: 'files', name: 'source' },
    { cat: 'files', name: 'file_copy' }, { cat: 'files', name: 'file_open' }, { cat: 'files', name: 'upload_file' },
    { cat: 'files', name: 'download_for_offline' }, { cat: 'files', name: 'cloud_sync' }, { cat: 'files', name: 'backup' },
    { cat: 'files', name: 'restore' }, { cat: 'files', name: 'history' }, { cat: 'files', name: 'archive' },
    { cat: 'files', name: 'unarchive' }, { cat: 'files', name: 'delete' }, { cat: 'files', name: 'request_page' },

    // Tech & Code
    { cat: 'tech', name: 'code' }, { cat: 'tech', name: 'terminal' }, { cat: 'tech', name: 'code_blocks' },
    { cat: 'tech', name: 'developer_mode' }, { cat: 'tech', name: 'integration_instructions' }, { cat: 'tech', name: 'deployed_code' },
    { cat: 'tech', name: 'data_object' }, { cat: 'tech', name: 'bug_report' }, { cat: 'tech', name: 'memory' },
    { cat: 'tech', name: 'webhook' }, { cat: 'tech', name: 'dns' }, { cat: 'tech', name: 'database' },
    { cat: 'tech', name: 'storage' }, { cat: 'tech', name: 'cable' }, { cat: 'tech', name: 'router' },
    { cat: 'tech', name: 'lan' }, { cat: 'tech', name: 'computer' }, { cat: 'tech', name: 'desktop_windows' },
    { cat: 'tech', name: 'laptop' }, { cat: 'tech', name: 'smartphone' }, { cat: 'tech', name: 'tablet' },
    { cat: 'tech', name: 'keyboard' }, { cat: 'tech', name: 'mouse' }, { cat: 'tech', name: 'devices' },
    { cat: 'tech', name: 'developer_board' }, { cat: 'tech', name: 'power' }, { cat: 'tech', name: 'memory_alt' },
    { cat: 'tech', name: 'rocket_launch' }, { cat: 'tech', name: 'science' }, { cat: 'tech', name: 'biotech' },
    { cat: 'tech', name: 'architecture' }, { cat: 'tech', name: 'engineering' },
    { cat: 'tech', name: 'android' }, { cat: 'tech', name: 'watch' }, { cat: 'tech', name: 'tv' },
    { cat: 'tech', name: 'print' }, { cat: 'tech', name: 'scanner' }, { cat: 'tech', name: 'battery_full' },
    { cat: 'tech', name: 'battery_charging_full' }, { cat: 'tech', name: 'device_hub' }, { cat: 'tech', name: 'sim_card' },
    { cat: 'tech', name: 'usb' }, { cat: 'tech', name: 'bluetooth' }, { cat: 'tech', name: 'wifi' },
    { cat: 'tech', name: 'signal_cellular_alt' }, { cat: 'tech', name: 'nfc' }, { cat: 'tech', name: 'monitor' },
    { cat: 'tech', name: 'display_settings' }, { cat: 'tech', name: 'screen_rotation' }, { cat: 'tech', name: 'cast' },
    { cat: 'tech', name: 'adb' }, { cat: 'tech', name: 'system_update' }, { cat: 'tech', name: 'gamepad' },
    { cat: 'tech', name: 'keyboard_alt' }, { cat: 'tech', name: 'headphones' }, { cat: 'tech', name: 'headset' },

    // Communication
    { cat: 'chat', name: 'mail' }, { cat: 'chat', name: 'email' }, { cat: 'chat', name: 'send' },
    { cat: 'chat', name: 'inbox' }, { cat: 'chat', name: 'mark_email_read' }, { cat: 'chat', name: 'drafts' },
    { cat: 'chat', name: 'chat' }, { cat: 'chat', name: 'forum' }, { cat: 'chat', name: 'chat_bubble' },
    { cat: 'chat', name: 'comment' }, { cat: 'chat', name: 'phone' }, { cat: 'chat', name: 'call' },
    { cat: 'chat', name: 'contact_phone' }, { cat: 'chat', name: 'contact_mail' }, { cat: 'chat', name: 'contacts' },
    { cat: 'chat', name: 'video_call' }, { cat: 'chat', name: 'voicemail' }, { cat: 'chat', name: 'announcement' },
    { cat: 'chat', name: 'unsubscribe' }, { cat: 'chat', name: 'forward_to_inbox' }, { cat: 'chat', name: 'phone_in_talk' },
    { cat: 'chat', name: 'ring_volume' }, { cat: 'chat', name: 'message' }, { cat: 'chat', name: 'sms' },
    { cat: 'chat', name: 'reviews' }, { cat: 'chat', name: 'rate_review' }, { cat: 'chat', name: 'feedback' },
    { cat: 'chat', name: 'question_answer' }, { cat: 'chat', name: 'speaker_notes' }, { cat: 'chat', name: 'campaign' },
    { cat: 'chat', name: 'rss_feed' }, { cat: 'chat', name: 'alternate_email' }, { cat: 'chat', name: 'connect_without_contact' },

    // Media & Creative
    { cat: 'media', name: 'image' }, { cat: 'media', name: 'photo' }, { cat: 'media', name: 'photo_camera' },
    { cat: 'media', name: 'movie' }, { cat: 'media', name: 'videocam' }, { cat: 'media', name: 'video_file' },
    { cat: 'media', name: 'music_note' }, { cat: 'media', name: 'mic' }, { cat: 'media', name: 'headphones' },
    { cat: 'media', name: 'headset' }, { cat: 'media', name: 'audiotrack' }, { cat: 'media', name: 'play_arrow' },
    { cat: 'media', name: 'pause' }, { cat: 'media', name: 'stop' }, { cat: 'media', name: 'brush' },
    { cat: 'media', name: 'palette' }, { cat: 'media', name: 'color_lens' }, { cat: 'media', name: 'design_services' },
    { cat: 'media', name: 'camera' }, { cat: 'media', name: 'animation' }, { cat: 'media', name: 'stadium' },
    { cat: 'media', name: 'skip_next' }, { cat: 'media', name: 'skip_previous' }, { cat: 'media', name: 'fast_forward' },
    { cat: 'media', name: 'fast_rewind' }, { cat: 'media', name: 'replay' }, { cat: 'media', name: 'volume_up' },
    { cat: 'media', name: 'volume_down' }, { cat: 'media', name: 'volume_off' }, { cat: 'media', name: 'speaker' },
    { cat: 'media', name: 'live_tv' }, { cat: 'media', name: 'radio' }, { cat: 'media', name: 'queue_music' },
    { cat: 'media', name: 'playlist_play' }, { cat: 'media', name: 'playlist_add' }, { cat: 'media', name: 'library_music' },
    { cat: 'media', name: 'album' }, { cat: 'media', name: 'equalizer' }, { cat: 'media', name: 'surround_sound' },
    { cat: 'media', name: 'play_circle' }, { cat: 'media', name: 'mic_off' }, { cat: 'media', name: 'podcasts' },
    { cat: 'media', name: 'add_photo_alternate' }, { cat: 'media', name: 'broken_image' }, { cat: 'media', name: 'panorama' },
    { cat: 'media', name: 'filter' }, { cat: 'media', name: 'filter_b_and_w' }, { cat: 'media', name: 'photo_album' },
    { cat: 'media', name: 'photo_library' }, { cat: 'media', name: 'slideshow' }, { cat: 'media', name: 'auto_fix_high' },
    { cat: 'media', name: 'style' }, { cat: 'media', name: 'wallpaper' }, { cat: 'media', name: 'portrait' },
    { cat: 'media', name: 'landscape' }, { cat: 'media', name: 'crop' }, { cat: 'media', name: 'rotate_right' },
    { cat: 'media', name: 'flip' }, { cat: 'media', name: 'stream' }, { cat: 'media', name: 'spatial_audio' },

    // Objects & Misc
    { cat: 'objects', name: 'anchor' }, { cat: 'objects', name: 'lightbulb' }, { cat: 'objects', name: 'umbrella' },
    { cat: 'objects', name: 'eco' }, { cat: 'objects', name: 'park' }, { cat: 'objects', name: 'shopping_cart' },
    { cat: 'objects', name: 'recycling' }, { cat: 'objects', name: 'local_fire_department' },
    { cat: 'objects', name: 'cruelty_free' }, { cat: 'objects', name: 'bolt' }, { cat: 'objects', name: 'flash_on' },
    { cat: 'objects', name: 'sports_esports' }, { cat: 'objects', name: 'stadia_controller' },
    { cat: 'objects', name: 'casino' }, { cat: 'objects', name: 'toys' },
    { cat: 'objects', name: 'local_offer' }, { cat: 'objects', name: 'sell' }, { cat: 'objects', name: 'card_giftcard' },
    { cat: 'objects', name: 'volunteer_activism' }, { cat: 'objects', name: 'pets' }, { cat: 'objects', name: 'local_florist' },
    { cat: 'objects', name: 'water_drop' }, { cat: 'objects', name: 'whatshot' }, { cat: 'objects', name: 'diamond' },
    { cat: 'objects', name: 'military_tech' }, { cat: 'objects', name: 'workspace_premium' }, { cat: 'objects', name: 'key' },
    { cat: 'objects', name: 'cake' }, { cat: 'objects', name: 'celebration' }, { cat: 'objects', name: 'wb_sunny' },
    { cat: 'objects', name: 'thermostat' }, { cat: 'objects', name: 'rainy' }, { cat: 'objects', name: 'ac_unit' },
    { cat: 'objects', name: 'water' }, { cat: 'objects', name: 'forest' }, { cat: 'objects', name: 'grass' },

    // Actions & UI
    { cat: 'actions', name: 'touch_app' }, { cat: 'actions', name: 'launch' }, { cat: 'actions', name: 'open_in_full' },
    { cat: 'actions', name: 'fullscreen' }, { cat: 'actions', name: 'fullscreen_exit' }, { cat: 'actions', name: 'autorenew' },
    { cat: 'actions', name: 'loop' }, { cat: 'actions', name: 'update' }, { cat: 'actions', name: 'pending' },
    { cat: 'actions', name: 'hourglass_empty' }, { cat: 'actions', name: 'timer' }, { cat: 'actions', name: 'alarm' },
    { cat: 'actions', name: 'done_all' }, { cat: 'actions', name: 'task_alt' }, { cat: 'actions', name: 'check_box' },
    { cat: 'actions', name: 'toggle_on' }, { cat: 'actions', name: 'toggle_off' }, { cat: 'actions', name: 'select_all' },
    { cat: 'actions', name: 'content_paste' }, { cat: 'actions', name: 'content_cut' }, { cat: 'actions', name: 'find_replace' },
    { cat: 'actions', name: 'manage_search' }, { cat: 'actions', name: 'drag_indicator' }, { cat: 'actions', name: 'reorder' },
    { cat: 'actions', name: 'swap_horiz' }, { cat: 'actions', name: 'swap_vert' }, { cat: 'actions', name: 'compare_arrows' },
    { cat: 'actions', name: 'link' }, { cat: 'actions', name: 'link_off' }, { cat: 'actions', name: 'pin' },
    { cat: 'actions', name: 'label_important' }, { cat: 'actions', name: 'low_priority' }, { cat: 'actions', name: 'priority_high' },
    { cat: 'actions', name: 'fiber_new' }, { cat: 'actions', name: 'star_rate' }, { cat: 'actions', name: 'date_range' },
    { cat: 'actions', name: 'today' }, { cat: 'actions', name: 'event_available' }, { cat: 'actions', name: 'watch_later' },

    // Activities & Sports
    { cat: 'activities', name: 'sports_soccer' }, { cat: 'activities', name: 'sports_basketball' }, { cat: 'activities', name: 'sports_tennis' },
    { cat: 'activities', name: 'sports_golf' }, { cat: 'activities', name: 'sports_baseball' }, { cat: 'activities', name: 'sports_football' },
    { cat: 'activities', name: 'sports_cricket' }, { cat: 'activities', name: 'sports_handball' }, { cat: 'activities', name: 'sports_hockey' },
    { cat: 'activities', name: 'sports_volleyball' }, { cat: 'activities', name: 'sports_mma' }, { cat: 'activities', name: 'sports_motorsports' },
    { cat: 'activities', name: 'fitness_center' }, { cat: 'activities', name: 'pool' }, { cat: 'activities', name: 'hiking' },
    { cat: 'activities', name: 'kayaking' }, { cat: 'activities', name: 'skateboarding' }, { cat: 'activities', name: 'surfing' },
    { cat: 'activities', name: 'snowboarding' }, { cat: 'activities', name: 'cycling' }, { cat: 'activities', name: 'directions_run' },
    { cat: 'activities', name: 'rowing' }, { cat: 'activities', name: 'self_improvement' }, { cat: 'activities', name: 'spa' },
    { cat: 'activities', name: 'accessibility' }, { cat: 'activities', name: 'sports_gymnastics' }, { cat: 'activities', name: 'kitesurfing' },
    { cat: 'activities', name: 'paragliding' }, { cat: 'activities', name: 'scuba_diving' }, { cat: 'activities', name: 'nordic_walking' },
    { cat: 'activities', name: 'downhill_skiing' }, { cat: 'activities', name: 'ice_skating' }, { cat: 'activities', name: 'sledding' },

    // Business & Finance
    { cat: 'business', name: 'work' }, { cat: 'business', name: 'business' }, { cat: 'business', name: 'business_center' },
    { cat: 'business', name: 'corporate_fare' }, { cat: 'business', name: 'apartment' }, { cat: 'business', name: 'store' },
    { cat: 'business', name: 'storefront' }, { cat: 'business', name: 'shopping_bag' }, { cat: 'business', name: 'payments' },
    { cat: 'business', name: 'credit_card' }, { cat: 'business', name: 'account_balance' }, { cat: 'business', name: 'bar_chart' },
    { cat: 'business', name: 'show_chart' }, { cat: 'business', name: 'trending_up' }, { cat: 'business', name: 'trending_down' },
    { cat: 'business', name: 'analytics' }, { cat: 'business', name: 'assessment' }, { cat: 'business', name: 'pie_chart' },
    { cat: 'business', name: 'timeline' }, { cat: 'business', name: 'receipt' }, { cat: 'business', name: 'warehouse' },
    { cat: 'business', name: 'factory' }, { cat: 'business', name: 'precision_manufacturing' }, { cat: 'business', name: 'support_agent' },
    { cat: 'business', name: 'badge' }, { cat: 'business', name: 'work_history' }, { cat: 'business', name: 'handshake' },
    { cat: 'business', name: 'real_estate_agent' }, { cat: 'business', name: 'request_quote' }, { cat: 'business', name: 'savings' },
    { cat: 'business', name: 'currency_exchange' }, { cat: 'business', name: 'attach_money' }, { cat: 'business', name: 'point_of_sale' },
    { cat: 'business', name: 'leaderboard' }, { cat: 'business', name: 'query_stats' }, { cat: 'business', name: 'manage_accounts' },
    { cat: 'business', name: 'account_balance_wallet' }, { cat: 'business', name: 'inventory' }, { cat: 'business', name: 'receipt_long' },

    // Home & Household
    { cat: 'home', name: 'house' }, { cat: 'home', name: 'cottage' }, { cat: 'home', name: 'villa' },
    { cat: 'home', name: 'cabin' }, { cat: 'home', name: 'bed' }, { cat: 'home', name: 'king_bed' },
    { cat: 'home', name: 'kitchen' }, { cat: 'home', name: 'bathroom' }, { cat: 'home', name: 'living' },
    { cat: 'home', name: 'dining' }, { cat: 'home', name: 'door_back' }, { cat: 'home', name: 'door_front' },
    { cat: 'home', name: 'garage' }, { cat: 'home', name: 'deck' }, { cat: 'home', name: 'yard' },
    { cat: 'home', name: 'fence' }, { cat: 'home', name: 'hot_tub' }, { cat: 'home', name: 'fireplace' },
    { cat: 'home', name: 'bathtub' }, { cat: 'home', name: 'shower' }, { cat: 'home', name: 'chair' },
    { cat: 'home', name: 'weekend' }, { cat: 'home', name: 'countertops' }, { cat: 'home', name: 'sensor_door' },
    { cat: 'home', name: 'window' }, { cat: 'home', name: 'microwave' }, { cat: 'home', name: 'dishwasher' },
    { cat: 'home', name: 'local_laundry_service' }, { cat: 'home', name: 'blender' }, { cat: 'home', name: 'outdoor_grill' },
    { cat: 'home', name: 'cleaning_services' }, { cat: 'home', name: 'carpenter' }, { cat: 'home', name: 'plumbing' },
    { cat: 'home', name: 'electrical_services' }, { cat: 'home', name: 'roofing' }, { cat: 'home', name: 'grass' },

    // Maps, Transit & Travel
    { cat: 'maps', name: 'map' }, { cat: 'maps', name: 'place' }, { cat: 'maps', name: 'location_on' },
    { cat: 'maps', name: 'my_location' }, { cat: 'maps', name: 'near_me' }, { cat: 'maps', name: 'directions' },
    { cat: 'maps', name: 'navigation' }, { cat: 'maps', name: 'route' }, { cat: 'maps', name: 'satellite_alt' },
    { cat: 'maps', name: 'layers' }, { cat: 'maps', name: 'terrain' }, { cat: 'maps', name: 'traffic' },
    { cat: 'maps', name: 'pin_drop' }, { cat: 'maps', name: 'flag' }, { cat: 'maps', name: 'tour' },
    { cat: 'maps', name: 'flight' }, { cat: 'maps', name: 'hotel' }, { cat: 'maps', name: 'luggage' },
    { cat: 'maps', name: 'beach_access' }, { cat: 'maps', name: 'travel_explore' }, { cat: 'maps', name: 'directions_bus' },
    { cat: 'maps', name: 'directions_subway' }, { cat: 'maps', name: 'directions_boat' }, { cat: 'maps', name: 'directions_car' },
    { cat: 'maps', name: 'two_wheeler' }, { cat: 'maps', name: 'electric_car' }, { cat: 'maps', name: 'tram' },
    { cat: 'maps', name: 'train' }, { cat: 'maps', name: 'subway' }, { cat: 'maps', name: 'local_airport' },
    { cat: 'maps', name: 'local_taxi' }, { cat: 'maps', name: 'commute' }, { cat: 'maps', name: 'connecting_airports' },
    { cat: 'maps', name: 'restaurant' }, { cat: 'maps', name: 'local_cafe' }, { cat: 'maps', name: 'nightlife' },
    { cat: 'maps', name: 'attractions' }, { cat: 'maps', name: 'local_gas_station' }, { cat: 'maps', name: 'local_parking' },
    { cat: 'maps', name: 'ev_station' }, { cat: 'maps', name: 'hail' }, { cat: 'maps', name: 'trip_origin' },

    // Social
    { cat: 'social', name: 'person_add' }, { cat: 'social', name: 'person_remove' }, { cat: 'social', name: 'group_add' },
    { cat: 'social', name: 'groups' }, { cat: 'social', name: 'tag' }, { cat: 'social', name: 'celebration' },
    { cat: 'social', name: 'emoji_emotions' }, { cat: 'social', name: 'sentiment_satisfied' }, { cat: 'social', name: 'sentiment_neutral' },
    { cat: 'social', name: 'sentiment_dissatisfied' }, { cat: 'social', name: 'mood' }, { cat: 'social', name: 'mood_bad' },
    { cat: 'social', name: 'face' }, { cat: 'social', name: 'waving_hand' }, { cat: 'social', name: 'handshake' },
    { cat: 'social', name: 'diversity_1' }, { cat: 'social', name: 'diversity_3' }, { cat: 'social', name: 'family_restroom' },
    { cat: 'social', name: 'follow_the_signs' }, { cat: 'social', name: 'contact_page' }, { cat: 'social', name: 'recommend' },
    { cat: 'social', name: 'reply' }, { cat: 'social', name: 'forward' }, { cat: 'social', name: 'how_to_vote' },
    { cat: 'social', name: 'volunteer_activism' }, { cat: 'social', name: 'not_interested' }, { cat: 'social', name: 'do_not_disturb' },
    { cat: 'social', name: 'sentiment_very_satisfied' }, { cat: 'social', name: 'rate_review' }, { cat: 'social', name: 'forum' },

    // Text & Formatting
    { cat: 'text', name: 'text_fields' }, { cat: 'text', name: 'title' }, { cat: 'text', name: 'subject' },
    { cat: 'text', name: 'notes' }, { cat: 'text', name: 'short_text' }, { cat: 'text', name: 'wrap_text' },
    { cat: 'text', name: 'format_align_left' }, { cat: 'text', name: 'format_align_center' }, { cat: 'text', name: 'format_align_right' },
    { cat: 'text', name: 'format_bold' }, { cat: 'text', name: 'format_italic' }, { cat: 'text', name: 'format_underlined' },
    { cat: 'text', name: 'format_strikethrough' }, { cat: 'text', name: 'format_list_bulleted' }, { cat: 'text', name: 'format_list_numbered' },
    { cat: 'text', name: 'format_quote' }, { cat: 'text', name: 'font_download' }, { cat: 'text', name: 'spellcheck' },
    { cat: 'text', name: 'translate' }, { cat: 'text', name: 'text_snippet' }, { cat: 'text', name: 'menu_book' },
    { cat: 'text', name: 'book' }, { cat: 'text', name: 'auto_stories' }, { cat: 'text', name: 'edit_note' },
    { cat: 'text', name: 'abc' }, { cat: 'text', name: 'draw' }, { cat: 'text', name: 'format_color_text' },
    { cat: 'text', name: 'highlight' }, { cat: 'text', name: 'text_format' }, { cat: 'text', name: 'format_size' },
    { cat: 'text', name: 'format_clear' }, { cat: 'text', name: 'horizontal_rule' }, { cat: 'text', name: 'table_rows' },
    { cat: 'text', name: 'insert_photo' }, { cat: 'text', name: 'insert_link' }, { cat: 'text', name: 'edit_document' },
];
